In [2]:
pip install jupyterlab-git

Collecting jupyterlab-git
  Downloading jupyterlab_git-0.53.0-py3-none-any.whl.metadata (3.7 kB)
Successfully installed fqdn-1.5.1 isoduration-20.11.0 jupyterlab-git-0.53.0 jupyterlab-git-core-0.53.0 nbdime-4.0.4 uri-template-1.3.0 webcolors-25.10.0
Note: you may need to restart the kernel to use updated packages.

In [8]:
import pandas as pd
web_logs=pd.read_csv(r"dataset\web_analytics_logs_10k.csv")
web_logs.head()

   session_id  user_id session_date  traffic_source      utm_source utm_medium  \
0     S000001     1399   2024-12-15   Instagram Ads    Facebook Ads    organic

In [10]:
top5_Pages_viewed = web_logs.sort_values(by='pages_viewed', ascending=False).head(5)
print(top5_Pages_viewed)

      session_id  user_id session_date traffic_source    utm_source utm_medium  \
7412    S007413     2003   2024-11-10    YouTube Ads  LinkedIn Ads    organic

In [12]:
import pandas as pd
crm_conversion=pd.read_csv(r"dataset\crm_conversions_10k.csv")
crm_conversion.head()

  conversion_id  user_id   lead_date conversion_date lead_stage  \
0       C000001     2661  2025-11-05       2025-06-23        SQL

In [24]:
import pandas as pd
ad_spend=pd.read_csv(r"dataset\ad_spend_10k.csv")
ad_spend.head()

   spend_id        date         channel         campaign      utm_source  \
0         1  2024-04-12     YouTube Ads     Campaign_XYZ  Organic Search

In [7]:
import pandas as pd

In [8]:
web_logs=pd.read_csv(r"dataset\web_analytics_logs_10k.csv")
web_logs.head()

In [9]:
crm_conversion=pd.read_csv(r"dataset\crm_conversions_10k.csv")
crm_conversion.head()

In [10]:
ad_spend=pd.read_csv(r"dataset\ad_spend_10k.csv")
ad_spend.head()

In [11]:
crm_conversion.isnull().sum()

In [1]:
import pandas as pd

In [3]:
web_logs=pd.read_csv(r"dataset\web_analytics_logs_10k.csv")
web_logs.head()

In [4]:
web_logs.isnull().sum()

In [7]:
web_logs.isnull().mean() * 100

In [8]:
web_logs['utm_campaign'] = web_logs['utm_campaign'].fillna('Unknown')

In [9]:
web_logs['city'] = web_logs['city'].fillna('Unknown')

In [10]:
web_logs.isnull().sum()

In [11]:
web_logs.duplicated().sum()

In [12]:
web_logs = web_logs.drop_duplicates()

In [15]:
web_logs.info()

In [16]:
web_logs.describe()

In [17]:
web_logs['traffic_source'].value_counts()

In [22]:
ad_spend.isnull().sum()

In [23]:
ad_spend['campaign'] = ad_spend['campaign'].fillna('Unknown')

In [24]:
ad_spend['date'] = pd.to_datetime(ad_spend['date'])

In [25]:
ad_spend['ctr'] = ad_spend['clicks'] / ad_spend['impressions']

In [26]:
ad_spend['cpc'] = ad_spend['ad_spend'] / ad_spend['clicks']

In [27]:
ad_spend['campaign'] = ad_spend['campaign'].fillna('Unknown')
ad_spend['utm_source'] = ad_spend['utm_source'].fillna('Unknown')

In [28]:
ad_spend.isnull().sum()

In [3]:
import pandas as pd
import os

In [6]:
BASE = r"dataset"
ad_spend = pd.read_csv(os.path.join(BASE, "ad_spend_10k.csv"))

In [7]:
ad_spend.groupby('channel')['ad_spend'].sum()

In [8]:
ad_spend.head()

In [3]:
import pandas as pd

ad_spend = pd.read_csv(
    "https://raw.githubusercontent.com/hitteshkharyal/Marketing-_ROI_Dashboard/main/dataset/ad_spend_10k.csv"
)

crm = pd.read_csv(
    "https://raw.githubusercontent.com/hitteshkharyal/Marketing-_ROI_Dashboard/main/dataset/crm_conversions_10k.csv"
)

web = pd.read_csv(
    "https://raw.githubusercontent.com/hitteshkharyal/Marketing-_ROI_Dashboard/main/dataset/web_analytics_logs_10k.csv"
)

print("Ad Spend Shape:", ad_spend.shape)
print("CRM Shape:", crm.shape)
print("Web Shape:", web.shape)

Ad Spend Shape: (10000, 11)
CRM Shape: (10000, 11)
Web Shape: (10000, 13)

In [22]:
print("Ad Spend Shape:", ad_spend.shape)
print("CRM Shape:", crm.shape)
print("Web Shape:", web.shape)

print("\nMissing Values")
print(ad_spend.isnull().sum())

Ad Spend Shape: (10000, 11)
CRM Shape: (10000, 11)
Web Shape: (10000, 13)

Missing Values
spend_id          0
date              0
channel           0
campaign        700
utm_source      700
utm_medium        0
utm_campaign      0
impressions       0
clicks            0
ad_spend          0
country           0
dtype: int64

In [28]:
ad_spend['campaign'] = ad_spend['campaign'].fillna('Unknown')
ad_spend['utm_source'] = ad_spend['utm_source'].fillna('Unknown')

In [29]:
print(ad_spend.isnull().sum())

spend_id        0
date            0
channel         0
campaign        0
utm_source      0
utm_medium      0
utm_campaign    0
impressions     0
clicks          0
ad_spend        0
country         0
dtype: int64

In [30]:
print("Ad Spend Duplicates:", ad_spend.duplicated().sum())
print("CRM Duplicates:", crm.duplicated().sum())
print("Web Duplicates:", web.duplicated().sum())

Ad Spend Duplicates: 0
CRM Duplicates: 0
Web Duplicates: 0

In [4]:
ad_spend.head()
crm.head()
web.head()

,session_id,user_id,session_date,traffic_source,utm_source,utm_medium,utm_campaign,device,city,country,pages_viewed,session_duration_sec,bounce_flag
0,S000001,1399,2024-12-15,Instagram Ads,Facebook Ads,organic,Festive Offer,Mobile,Delhi,Germany,15,3410,0
1,S000002,4352,2024-04-09,Organic Search,Organic Search,email,Brand Awareness,Desktop,Bangalore,Australia,18,1206,1
2,S000003,2935,2024-10-13,YouTube Ads,LinkedIn Ads,email,Retargeting,Desktop,Berlin,UK,4,3224,0
3,S000004,2272,2024-09-25,Google Ads,LinkedIn Ads,cpc,Summer Sale,Desktop,Bangalore,UK,10,2930,0
4,S000005,3390,2024-12-14,YouTube Ads,Google Ads,organic,Brand Awareness,Desktop,Mumbai,UK,2,1540,0

In [5]:
ad_spend.info()
crm.info()
web.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   spend_id      10000 non-null  int64
 1   date          10000 non-null  object
 2   channel       10000 non-null  object
 3   campaign      9300 non-null   object
 4   utm_source    9300 non-null   object
 5   utm_medium    10000 non-null  object
 6   utm_campaign  10000 non-null  object
 7   impressions   10000 non-null  int64
 8   clicks        10000 non-null  int64
 9   ad_spend      10000 non-null  float64
 10  country       10000 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 859.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   conversion_id      10000 non-null  object
 1   user_id            10000 non-null  int64
 2   lead_date          10000 non-null  object
 3   conversion_date    10000 non-null  object
 4   lead_stage         10000 non-null  object
 5   customer_journey   10000 non-null  object
 6   product            9200 non-null   object
 7   deal_value         10000 non-null  float64
 8   country            10000 non-null  object
 9   city               9200 non-null   object
 10  conversion_status  10000 non-null  object
dtypes: float64(1), int64(1), object(9)
memory usage: 859.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   session_id            10000 non-null  object
 1   user_id               10000 non-null  int64
 2   session_date          10000 non-null  object
 3   traffic_source        10000 non-null  object
 4   utm_source            10000 non-null  object
 5   utm_medium            10000 non-null  object
 6   utm_campaign          9400 non-null   object
 7   device                10000 non-null  object
 8   city                  9400 non-null   object
 9   country               10000 non-null  object
 10  pages_viewed          10000 non-null  int64
 11  session_duration_sec  10000 non-null  int64
 12  bounce_flag           10000 non-null  int64
dtypes: int64(4), object(9)
memory usage: 1015.8+ KB

In [6]:
ad_spend["CTR"] = (
    ad_spend["clicks"] / ad_spend["impressions"]
) * 100

In [7]:
ad_spend["CPC"] = (
    ad_spend["ad_spend"] / ad_spend["clicks"]
)

In [9]:
print(ad_spend.columns.tolist())

['spend_id', 'date', 'channel', 'campaign', 'utm_source', 'utm_medium', 'utm_campaign', 'impressions', 'clicks', 'ad_spend', 'country', 'CTR', 'CPC']

In [10]:
ad_spend[['channel', 'CTR', 'CPC']].head()

          channel       CTR        CPC
0     YouTube Ads  2.571475   0.653690
1  Organic Search  0.034825  53.278261
2    LinkedIn Ads  0.873884   1.973021
3      Google Ads  1.420772   0.201184
4    LinkedIn Ads  2.548427   0.464409